swagger: "2.0"
info:
  description: Southbound interface specification
  version: "4.0"
  title: Banking Services
host: 'bankingservices-sandbox.pagopa.it'
basePath: /api/pagopa/banking/v4.0/utils/
tags:
- name: APIs
  description: Validator Controller
paths:
  /validate-account-holder:
    post:
      tags:
      - APIs
      summary: ""
      operationId: validateAccountHolderUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Auth-Schema
        type: string
        required: true
      - in: header
        name: Api-Key
        type: string
        required: true
      - in: body
        name: inputModel
        description: Validates the provided account number and holder data.
        required: true
        schema:
          $ref: '#/definitions/ValidateAccountHolderRequestModel'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseModelValidateAccountHolderResponseModel'
        "400":
          description: BadRequest
          schema:
            $ref: '#definitions/Response400ErrorModel'
        "403":
          description: BadRequest
          schema:
            $ref: '#definitions/Response400ErrorModel'
definitions:
  AccountHolderRequestModel:
    type: object
    required:
    - type
    properties:
      fiscalCode:
        type: string
        description: The identification data of the account holder, if natural person (Italian Codice Fiscale). Required field if type == 'PERSON_NATURAL'.
      taxCode:
        type: string
        description: The identification data of the account holder, if legal person (Italian Codice Fiscale Aziendale). Required field if type == 'PERSON_LEGAL'.
      type:
        type: string
        description: The type of account holder, used to decline the holderId.
        enum:
        - PERSON_LEGAL
        - PERSON_NATURAL
      vatCode:
        type: string
        description: The identification data of the account holder, if legal person (Italian Partita IVA). Required field if type == 'PERSON_LEGAL'.
    title: AccountHolderRequestModel
  AccountHolderResponseModel:
    type: object
    properties:
      fiscalCode:
        type: string
        description: The identification data of the account holder, if natural person (Italian Codice Fiscale). Required field if type == 'PERSON_NATURAL'.
      type:
        type: string
        description: The type of account holder, used to decline the holderId.
        enum:
        - PERSON_LEGAL
        - PERSON_NATURAL
    title: AccountHolderResponseModel
  AccountRequestModel:
    type: object
    properties:
      bicCode:
        type: string
        description: The international bic code.
      value:
        type: string
        description: The account number.
      valueType:
        type: string
        description: The account number type.
        enum:
        - IBAN
    title: AccountRequestModel
  AccountResponseModel:
    type: object
    required:
    - value
    - valueType
    properties:
      value:
        type: string
        description: The account number.
      valueType:
        type: string
        description: The account number type.
        enum:
        - IBAN
    title: AccountResponseModel
  BankInfoModel:
    type: object
    properties:
      bicCode:
        type: string
      branchName:
        type: string
      businessName:
        type: string
      city:
        type: string
      countryCode:
        type: string
    title: BankInfoModel
  ErrorModel:
    type: object
    properties:
      code:
        type: string
      description:
        type: string
    title: ErrorModel
  ResponseModelValidateAccountHolderResponseModel:
    type: object
    properties:
      status:
        type: string
      payload:
        type: object
    title: ValidateAccountHolderResponseModel
  ValidateAccountHolderRequestModel:
    type: object
    x-nullable: true
    properties:
      account:
        description: The account information
        $ref: '#/definitions/AccountRequestModel'
      accountHolder:
        description: The account holder information
        $ref: '#/definitions/AccountHolderRequestModel'
    title: ValidateAccountHolderRequestModel
  ValidateAccountHolderResponseModel:
    type: object
    properties:
      validationStatus:
        type: string
        description: The validation result.
        enum:
        - KO
        - OK
      account:
        description: The account information.
        $ref: '#/definitions/AccountResponseModel'
      accountHolder:
        description: The account holder information.
        $ref: '#/definitions/AccountHolderResponseModel'
      bankInfo:
        description: The bank information.
        $ref: '#/definitions/BankInfoModel'
        x-nullable: true
    title: ValidateAccountHolderResponseModel
  Response400ErrorModel:
    type: object
    required:
    - status
    properties:
      status:
        type: string
      errors:
        type: array
        items:
          $ref: '#/definitions/ErrorModel'
