swagger: '2.0'
info:
  title: PagoPA Search Payment Instruments
  version: '4.0.0'
host: '<domain-for-pagopa>'
basePath: /api/pagopa/banking/v4.0/utils
tags:
  - name: PagoPA Search Payment Instruments Service
paths:
  '/payment-instruments/search':
    post:
      tags:
        - PagoPA Search Payment Instruments Service
      operationId: searchPaymentInstrumentsUsingPOST
      summary: Searches for the known payment instruments.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: singlePaymentModelInput
          description: singlePaymentModelInput
          required: true
          schema:
            $ref: '#/definitions/SearchPaymentInstrumentsModelInput'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SearchPaymentInstrumentsModelOutput'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
      deprecated: false
  
  '/payment-instruments/{searchRequestId}':
    get:
      tags:
        - PagoPA Search Payment Instruments Service
      operationId: searchPaymentInstrumentsUsingGET
      summary: Retrieves an asynchronous search request.
      produces:
        - application/json
      parameters:
        - in: path
          name: searchRequestId
          type: string
          description: singlePaymentModelInput
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SearchPaymentInstrumentsModelOutput'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
      deprecated: false
  

definitions:

  SearchPaymentInstrumentsModelInput:
    type: object
    properties:
      fiscalCode:
        type: string
        example: "ABCDEF12L12A123K"
        description: "The fiscal code of the payment intrument owner to search for."
      productType:
        type: string
        enum: [PP, DB, PRIVATIVE]
        description: "The type of the payment intrument to search for."
      abiCode:
        type: string
        example: "12345"
        description: "The ABI code of the payment intrument issuer to search for."
      panCode:
        type: string
        example: "123456789012345"
        description: "The PAN of the payment intrument to search for."
      acquirerId:
        type: string
        example: ""
        description: "TBD"
    required: [fiscalCode, productType]
    title: SearchPaymentInstrumentsModelInput

  SearchPaymentInstrumentsModelOutput:
    type: object
    properties:
      status:
        type: string
        enum: [OK, KO]
      errors:
        type: array
        items:
          $ref: '#/definitions/ErrorModel'
      payload:
        $ref: '#/definitions/SearchPaymentInstrumentsModelOutputPayload'
    title: ValidateAccountHolderModelOutput

  MessagesModelOutput:
    type: array
    items:
      $ref: "#/definitions/MessagesElementModelOutput"
    title: MessagesModelOutput

  MessagesElementModelOutput:
    type: object
    properties:
      serviceProviderName:
        type: string
      retrievedInstrumentsCount:
        type: integer
      executionStatus:
        type: string
    title: MessagesElementModelOutput

  DataModelOutput:
    type: array
    items:
      $ref: "#/definitions/DataElementModelOutput"
    title: DataModelOutput

  DataElementModelOutput:
    type: object
    properties:
      abiCode:
        type: string
      panCode:
        type: string
      expiringDate:
        type: string
      productType:
        type: string
        enum: [CREDIT, PREPAID, DEBIT, PRIVATIVE]
      validityStatus:
        type: string
        enum: [VALID, BLOCK_REVERSIBLE]
      paymentNetwork:
        type: string
        enum: [MAESTRO, MASTERCARD, VISA_ELECTRON, VISA_CLASSIC, VPAY]
    title: DataElementModelOutput

  SearchPaymentInstrumentsModelOutputPayload:
    type: object
    properties:
      searchRequestId:
        type: string
        description: "The search request ID."
      paymentInstruments:
        $ref: "#/definitions/DataModelOutput"
      searchRequestMetadata:
        $ref: "#/definitions/MessagesModelOutput"
    required: [requestId, data, messages]
    title: SearchPaymentInstrumentsModelOutputPayload

  ErrorModel:
    type: object
    properties:
      code:
        type: string
      description:
        type: string
      params:
        type: string
    title: ErrorModel